In [2]:
import pandas as pd

In [19]:
X_train = pd.read_csv('data/Training_set_values.csv', index_col='id')
X_test = pd.read_csv('data/Test_set_values.csv', index_col='id')
y = pd.read_csv('data/Training_set_labels.csv', index_col='id')

In [20]:
X_train.head()

,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,basin,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
id,,,,,,,,,,,,,,,,,,,,,
69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,Lake Nyasa,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,Lake Victoria,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,Pangani,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,Ruvuma / Southern Coast,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,Lake Victoria,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [21]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 69572 to 26348
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             59400 non-null  float64
 1   date_recorded          59400 non-null  object
 2   funder                 55765 non-null  object
 3   gps_height             59400 non-null  int64
 4   installer              55745 non-null  object
 5   longitude              59400 non-null  float64
 6   latitude               59400 non-null  float64
 7   wpt_name               59400 non-null  object
 8   num_private            59400 non-null  int64
 9   basin                  59400 non-null  object
 10  subvillage             59029 non-null  object
 11  region                 59400 non-null  object
 12  region_code            59400 non-null  int64
 13  district_code          59400 non-null  int64
 14  lga                    59400 non-null  object
 15  ward                   59400 non-null  object
 16  population             59400 non-null  int64
 17  public_meeting         56066 non-null  object
 18  recorded_by            59400 non-null  object
 19  scheme_management      55523 non-null  object
 20  scheme_name            31234 non-null  object
 21  permit                 56344 non-null  object
 22  construction_year      59400 non-null  int64
 23  extraction_type        59400 non-null  object
 24  extraction_type_group  59400 non-null  object
 25  extraction_type_class  59400 non-null  object
 26  management             59400 non-null  object
 27  management_group       59400 non-null  object
 28  payment                59400 non-null  object
 29  payment_type           59400 non-null  object
 30  water_quality          59400 non-null  object
 31  quality_group          59400 non-null  object
 32  quantity               59400 non-null  object
 33  quantity_group         59400 non-null  object
 34  source                 59400 non-null  object
 35  source_type            59400 non-null  object
 36  source_class           59400 non-null  object
 37  waterpoint_type        59400 non-null  object
 38  waterpoint_type_group  59400 non-null  object
dtypes: float64(3), int64(6), object(30)
memory usage: 18.1+ MB

In [22]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14850 entries, 50785 to 68707
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   amount_tsh             14850 non-null  float64
 1   date_recorded          14850 non-null  object
 2   funder                 13981 non-null  object
 3   gps_height             14850 non-null  int64
 4   installer              13973 non-null  object
 5   longitude              14850 non-null  float64
 6   latitude               14850 non-null  float64
 7   wpt_name               14850 non-null  object
 8   num_private            14850 non-null  int64
 9   basin                  14850 non-null  object
 10  subvillage             14751 non-null  object
 11  region                 14850 non-null  object
 12  region_code            14850 non-null  int64
 13  district_code          14850 non-null  int64
 14  lga                    14850 non-null  object
 15  ward                   14850 non-null  object
 16  population             14850 non-null  int64
 17  public_meeting         14029 non-null  object
 18  recorded_by            14850 non-null  object
 19  scheme_management      13881 non-null  object
 20  scheme_name            7758 non-null   object
 21  permit                 14113 non-null  object
 22  construction_year      14850 non-null  int64
 23  extraction_type        14850 non-null  object
 24  extraction_type_group  14850 non-null  object
 25  extraction_type_class  14850 non-null  object
 26  management             14850 non-null  object
 27  management_group       14850 non-null  object
 28  payment                14850 non-null  object
 29  payment_type           14850 non-null  object
 30  water_quality          14850 non-null  object
 31  quality_group          14850 non-null  object
 32  quantity               14850 non-null  object
 33  quantity_group         14850 non-null  object
 34  source                 14850 non-null  object
 35  source_type            14850 non-null  object
 36  source_class           14850 non-null  object
 37  waterpoint_type        14850 non-null  object
 38  waterpoint_type_group  14850 non-null  object
dtypes: float64(3), int64(6), object(30)
memory usage: 4.5+ MB

In [24]:
y.value_counts()

status_group
functional                 32259
non functional             22824
functional needs repair     4317
dtype: int64